class ARAnalyticsConstants {
  static const String USERDEFAULTS_USER_LAST_CHECKIN_DATE =
      "ARANALYTICS_USER_LAST_CHECKIN_DATE";
  static const String USERDEFAULTS_NUM_CHECKINS = "ARANALYTICS_NUM_CHECKINS";
  static const String USERDEFAULTS_NUM_SESSIONS = "ARANALYTICS_NUM_SESSIONS";
  static const String USERDEFAULTS_NUM_GOAL1 = "ARANALYTICS_NUM_GOAL1";
  static const String USERDEFAULTS_NUM_GOAL2 = "ARANALYTICS_NUM_GOAL2";
  static const String USERDEFAULTS_NUM_POSTS = "ARANALYTICS_NUM_POSTS";
  static const String USERDEFAULTS_INSTALL_METADATA =
      "ARANALYTICS_INSTALL_METADATA";
  static const String USERDEFAULTS_HASUSERPURCHASED =
      "USERDEFAULTS_HASUSERPURCHASED";
  static const String USERDEFAULTS_USERPURCHASECOUNT =
      "USERDEFAULTS_USERPURCHASECOUNT";
  static const String USERDEFAULTS_FORCEPRO = "ARANALYTICS_FORCEPRO";

  static const String USERDEFAULTS_IS_USER_ENGAGED =
      "ARANALYTICS_ISUSERENGAGED";

  static const String USERDEFAULTS_LEGACY_UPDATE_VERSION_TRACKED_BEFORE =
      "ARANALYTICS_LEGACY_UPDATE_VERSION_TRACKED_BEFORE";
  static const String USERDEFAULTS_LEGACY_UPDATE_VERSION =
      "RMANALYTICS_LEGACY_UPDATE_VERSION";
  static const String USERDEFAULTS_LEGACY_UPDATE_BUILD =
      "RMANALYTICS_LEGACY_UPDATE_BUILD";

  static const String USERDEFAULTS_APPSFLYER_INSTALL_TYPE =
      "ARANALYTICS__APPSFLYER_INSTALL_TYPE";
  static const String USERDEFAULTS_APPSFLYER_INSTALL_MEDIASOURCE =
      "ARANALYTICS__APPSFLYER_INSTALL_MEDIASOURCE";
  static const String USERDEFAULTS_APPSFLYER_INSTALL_CAMPAIGN =
      "ARANALYTICS__APPSFLYER_INSTALL_CAMPAIGN";

  static const String USERDEFAULTS_PURCHASE_TRACKED_BEFORE =
      "ARANALYTICS_purchaseEventTrackedBefore";
  static const String USERDEFAULTS_PURCHASE_TRACKED_BEFORE_WITH_PRODUCT_ID =
      "ARANALYTICS_purchaseEventTrackedBefore_%@";

  static const String USERDEFAULTS_LAST_APP_SESSION_SOURCE_UPDATE =
      "ARANALYTICS_LAST_APP_SESSON_SOURCE_UPDATE";

  static const String USERDEFAULTS_TRACK_ONE_TIME_EVENT =
      "ARANALYTICS_trackedOneTimeEvent";
  static const String USERDEFAULTS_TRACK_ONE_TIME_EVENT_WITH_NAME =
      "RMANALYTICS_trackedOneTimeEvent_%@";

  static const String USERDEFAULTS_USER_PHOTOGRAPHER_TYPE =
      "USERPARAM_PHOTOGRAPHER_TYPE";
  static const String USERDEFAULTS_USER_PHOTO_TYPE = "USERPARAM_PHOTO_TYPE";

  static const String ARCONFIG_FILENAME = "ARConfig.plist";

  static const String APP_ID = "6748644645";
  static const String USER_ID = "userId12345";

  static const String EMAIL_PREFIX = "SA Cheats";
  static const String SUPPORT_EMAIL = "info@arleven.com";

  static const APP_NAME = "SA Cheats";

  static const String REVENUE_CAT_API_KEY_IOS =
      "appl_MaGFVjAzyrPOwjQKpdLeYondNwH";

  static const String REVENUE_CAT_API_KEY_ANDROID =
      "appl_MaGFVjAzyrPOwjQKpdLeYondNwH";
  static const String AMPLITUDE_API_KEY = "8381de8f586ff66fba9c70735ce5534b";
}
