final Map<String, dynamic> arConfig = {
  "Common": {
    "AppName": "",
    "AppId": "",
    "AppId_Backup": "",
    "AppSubtitle": "x",
    "AppWebsite": "x",
    "PrivacyPolicy": "",
    "Terms": "",
    "ShareMessage": "x",
    "InstagramAccount": "x",
    "InstagramHashtag": "x",
    "InstagramURL": "x",
    "InstagramWebURL": "x",
  },
  "Notifications": {
    "OneSignalAppId": "",
    "LocalPushOn": false,
    "LocalFrequency": [
      3,
      6,
      10,
      16,
      21,
      26,
      33,
      38,
      43,
      48,
      53,
      58,
      63,
      68,
      73,
      88,
    ],
    "LocalMessages": ["👋"],
  },
  "Support": {
    "SupportAppName": "",
    "email": "",
    "support_topics": [
      "Feed post Reposting",
      "Story Reposting",
      "Purchase & Subscription",
      "Hashtags & Scheduling Feature",
      "New Feature Request",
      "Something Else",
    ],
  },
  "Analytics": {
    "BranchKeyProd": "x",
    "BranchKeyDev": "x",
    "MixpanelTokenDev": "x",
    "MixpanelTokenProd": "x",
    "AmplitudeTokenDev": "",
    "AmplitudeTokenBeta": "",
    "AmplitudeTokenProd": "",
    "AmplitudeTokenDev_Backup": "",
    "AppsFlyerKeyDev": "",
    "AppsFlyerKeyProd": "",
    "FlurryKeyDev": "x",
    "FlurryKeyProd": "x",
    "FlurryCrashReportingEnabled": false,
    "TokenDev_Backup": "x",
  },
  "LTUIKit": {
    "Onboarding": {"WelcomeMessage": "x", "BackgroundImage": "x"},
    "Home": {
      "TitleFont": "Baskerville",
      "UseImages": false,
      "UseInstafeed": true,
      "UseVideo": false,
      "UseStoreHeaderIcon": true,
      "UseCircularCrop": false,
      "ImageNames": ["homeImage3.jpg"],
      "VideoName": "",
    },
    "Splash": {
      "Title": "x",
      "AnimationDuration": 3,
      "FontSize": 16,
      "FontName": "Baskerville",
      "FontKerning": 12,
      "ShouldShowPrivacyRequestOnSplash": true,
    },
  },
  "Instafeed": {
    "suggestedInstagramLink": "x",
    "NumCellsPerRow": "3",
    "OpensInstagram": false,
    "DefaultURLs": ["x"],
  },
  "Hashtag": {"TagSet": "repostplus"},
  "Product": {
    "RevenueCatKeyDev": "",
    "RevenueCatKeyProd": "",
    "RevenueCatKeyDev_Backup": "",
  },
  "Tags": {"Prefix": "x", "CustomTag": "x"},
  "Backend": {
    "BackendApplicationId": "",
    "BackendClientKey": "",
    "BackendServer": "",
  },
  "BackendDev": {
    "BackendApplicationId": "",
    "BackendClientKey": "",
    "BackendServer": "",
  },
  "Review": {
    "PFM_Exclusions": ["1"],
  },
};
